# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jean's Blog
tagline:             "It's not a bug, it's a feature."
description:         A blog by software engineer and food enthusiast.
url:                 https://jean-njoroge.github.io
baseurl:             https://jean-njoroge.github.io/
paginate:            5
#google_analytics_id: UA-56228338-1

# About/contact
author:
  name:              Jean Njoroge
  #url:               https://facebook.com/haisum
  email:             shirojean@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-feed

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
